---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - localstack.kb.dev
  resources:
  - s3buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - localstack.kb.dev
  resources:
  - s3buckets/finalizers
  verbs:
  - update
- apiGroups:
  - localstack.kb.dev
  resources:
  - s3buckets/status
  verbs:
  - get
  - patch
  - update
